"""Integration test against real GitLab — uses the existing project.

Requires GITLAB_URL, GITLAB_TOKEN, GITLAB_PROJECT_ID env vars.
Marked with @pytest.mark.integration — skipped by default.
Run with: pytest -m integration reagent/tests/test_gitlab_integration.py -v -s
"""

from __future__ import annotations

import os
import time
import uuid

import pytest

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from gitlab_client import GitLabClient

TOKEN = os.getenv("GITLAB_TOKEN", "")
URL = os.getenv("GITLAB_URL", "https://gitlab.com")
PROJECT_ID = os.getenv("GITLAB_PROJECT_ID", "")

if not TOKEN or not PROJECT_ID:
    pytestmark = pytest.mark.skip("GITLAB_TOKEN or GITLAB_PROJECT_ID not set")
else:
    pytestmark = pytest.mark.integration


@pytest.fixture(scope="module")
def gl():
    """Create a GitLab client connected to the existing project."""
    client = GitLabClient(url=URL, token=TOKEN, project_id=PROJECT_ID)
    return client


UNIQUE = uuid.uuid4().hex[:6]
BRANCH = f"test-{UNIQUE}"
CONTRACT_NAME = f"HelloToken{UNIQUE}"
CONTRACT_FILE = f"contracts/{CONTRACT_NAME}.sol"
GOVERNANCE_FILE = f"contracts/Governance{UNIQUE}.sol"
TEST_FILE = f"tests/test_governance_{UNIQUE}.js"


def test_00_seed_repo(gl):
    """Seed the empty repo with an initial commit so main branch exists."""
    try:
        gl.list_branches()
    except Exception:
        pass
    branches = gl.list_branches()
    if branches:
        print("\n  Repo already has branches — skipping seed")
        return
    # Empty repo — create initial commit with a README
    gl.commit_files("main", "Initial commit", [
        {"action": "create", "file_path": "README.md", "content": "# Reagent Test Project\n\nSmart contract orchestration test repo.\n"},
    ])
    time.sleep(2)
    print("\n  Seeded repo with initial commit on main")


def test_01_list_branches(gl):
    """Default branch should exist."""
    branches = gl.list_branches()
    names = [b["name"] for b in branches]
    print(f"\n  Branches: {names}")
    assert any(n in names for n in ("main", "master"))


def test_02_create_branch(gl):
    """Create a feature branch."""
    default_branch = "main"
    branches = gl.list_branches()
    if branches and branches[0]["name"] == "master":
        default_branch = "master"
    result = gl.create_branch(BRANCH, ref=default_branch)
    assert result["name"] == BRANCH
    print(f"\n  Created branch: {BRANCH}")


def test_03_create_file(gl):
    """Create a Solidity contract file on the feature branch."""
    result = gl.create_file(
        CONTRACT_FILE,
        f"// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\ncontract {CONTRACT_NAME} {{ string public name = '{CONTRACT_NAME}'; }}",
        BRANCH,
        f"Add {CONTRACT_NAME} contract",
    )
    assert result["file_path"] == CONTRACT_FILE


def test_04_commit_files(gl):
    """Batch-commit multiple files at once."""
    actions = [
        {
            "action": "create",
            "file_path": GOVERNANCE_FILE,
            "content": f"// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\ncontract Governance{UNIQUE} {{ }}",
        },
        {
            "action": "create",
            "file_path": TEST_FILE,
            "content": "const { expect } = require('chai');\n\ndescribe('Governance', () => { it('should deploy', async () => {}); });",
        },
    ]
    result = gl.commit_files(BRANCH, "Add governance contract and tests", actions)
    assert result["short_id"] is not None
    print(f"\n  Commit: {result['short_id']}")


def test_05_read_file(gl):
    """Read back the file we just created."""
    content = gl.read_file(CONTRACT_FILE, ref=BRANCH)
    assert CONTRACT_NAME in content


def test_06_get_repo_tree(gl):
    """Verify the repo tree shows our files."""
    tree = gl.get_repo_tree(ref=BRANCH, recursive=True)
    paths = [item["path"] for item in tree]
    print(f"\n  Tree paths: {paths}")
    assert any(CONTRACT_NAME in p for p in paths)


def test_07_update_file(gl):
    """Update the contract file."""
    gl.update_file(
        CONTRACT_FILE,
        f"// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\ncontract {CONTRACT_NAME} {{ string public name = '{CONTRACT_NAME}V2'; uint8 public decimals = 18; }}",
        BRANCH,
        f"Upgrade {CONTRACT_NAME} to V2",
    )
    content = gl.read_file(CONTRACT_FILE, ref=BRANCH)
    assert f"{CONTRACT_NAME}V2" in content


def test_08_create_merge_request(gl):
    """Open a merge request from the feature branch."""
    result = gl.create_merge_request(
        "Add HelloToken & Governance contracts",
        BRANCH,
        description="## Summary\n- Added HelloToken contract (V2)\n- Added Governance contract\n- Added test stubs\n\nAuto-generated by reagent integration test.",
    )
    assert result["iid"] is not None
    assert result["web_url"] is not None
    print(f"\n  MR URL: {result['web_url']}")
    gl._test_mr_iid = result["iid"]


def test_09_merge_merge_request(gl):
    """Merge the MR."""
    mr_iid = getattr(gl, "_test_mr_iid", None)
    if not mr_iid:
        pytest.skip("No MR created")
    # Small delay to let GitLab process
    time.sleep(2)
    result = gl.merge_merge_request(mr_iid, should_remove_source_branch=False)
    assert result["merged"] is True
    print(f"\n  Merged MR !{mr_iid}")


def test_10_delete_branch(gl):
    """Delete the feature branch after merge."""
    result = gl.delete_branch(BRANCH)
    assert result["deleted"] is True
    print(f"\n  Deleted branch: {BRANCH}")


def test_11_create_issue(gl):
    """Create a tracking issue."""
    result = gl.create_issue(
        "Integration test passed",
        "All stages completed successfully via reagent integration test.",
    )
    assert result["iid"] is not None
    print(f"\n  Issue: {result['web_url']}")


def test_12_add_issue_note(gl):
    """Add a note to the issue."""
    result = gl.add_issue_note(1, "Integration test completed — all stages passed")
    assert result["body"] is not None


def test_13_delete_file(gl):
    """Delete a file from main."""
    # Create a temp file first, then delete it
    gl.create_file("temp_cleanup.txt", "temporary", "main", "Add temp file")
    result = gl.delete_file("temp_cleanup.txt", "main", "Cleanup temp file")
    assert result["deleted"] is True


def test_14_search_code(gl):
    """Search for code in the project (indexing may be delayed on GitLab.com)."""
    results = gl.search_code("HelloToken")
    print(f"\n  Search results: {len(results)}")
    # GitLab.com search indexing is async — may return 0 immediately after push
    if len(results) >= 1:
        assert any("HelloToken" in str(r) for r in results)
    else:
        print("  (Search index not yet updated — expected on GitLab.com)")


def test_15_final_repo_link(gl):
    """Print the final repo link."""
    project_url = f"{URL}/{gl.project.path_with_namespace}" if hasattr(gl.project, 'path_with_namespace') else f"{URL}/project/{gl.project_id}"
    print(f"\n{'='*60}")
    print(f"  REPO LINK: {project_url}")
    print(f"{'='*60}")
